version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      commit-message:
          prefix: 'chore(github-actions)'
      open-pull-requests-limit: 100


    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      commit-message:
          prefix: 'chore(npm)'
      open-pull-requests-limit: 100
