name: On pull request updated
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main

permissions:
    pull-requests: write
    contents: write
    issues: write
    repository-projects: write

jobs:
    run:
        name: Quality gate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v5
              with:
                  persist-credentials: false
            - name: Install Node and Restore Cache
              uses: actions/setup-node@v6
              with:
                  node-version: 18
                  check-latest: true
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'
            - name: Install Dependencies
              run: npm ci --ignore-scripts || npm i  --ignore-scripts
            - name: Build
              run: npm run build
            - name: Basic success
              run: node dist/cli.js README.md README.txt
            - name: Force overwrite
              run: node dist/cli.js --force README.md README.txt

    dependabot:
        continue-on-error: true
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v2.4.0
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'
            - name: Add a label for all production dependencies
              continue-on-error: true
              if: ${{ steps.metadata.outputs.dependency-type == 'direct:production' }}
              run: gh pr edit "$PR_URL" --add-label "production"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
            - name: Add a label for all major updates
              continue-on-error: true
              if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' }}
              run: gh pr edit "$PR_URL" --add-label "major"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
            - name: Github Actions Approve PR
              continue-on-error: true
              run: gh pr review --approve "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

    auto-merge:
        continue-on-error: true
        runs-on: ubuntu-latest
        if: ${{ github.event.pull_request.draft == false }}
        steps:
            - name: Enable auto-merge for this PR
              continue-on-error: true
              run: gh pr merge --auto --rebase "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
